# variables.tf  基础值处理
aws_region                   = "cn-northwest-1"
domain_name                  = "wujiankeji.cn"
eks_cluster_name_prefix      = "private-cloud-prod"
certificate_expiration_email = "qukaige@beijingwujian.com"
s3_bucket_name               = "private-cloud-prod-2"
namespace_id                 = ""
namespace_secret             = ""
environments_internal_names  = ["prod"]