## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only)
policy: sync
domainFilters:
  - ${hostname}
image:
  repository: registry.cn-beijing.aliyuncs.com/kaigequ/external-dns
  tag: v0.13.5