promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki-stack.loki.svc.cluster.local:3100/loki/api/v1/push
  image:
    pullPolicy: IfNotPresent
    registry: registry.cn-beijing.aliyuncs.com
    repository: kaigequ/promtail
    tag: 2.9.3
loki:
  persistence:
    enabled: true
    size: 30Gi
    storageClassName: gp2
  config:
    chunk_store_config:
      max_look_back_period: 60d
    table_manager:
      retention_period: 60d
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-beijing.aliyuncs.com/kaigequ/loki
    tag: 2.6.1